services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - next_cms_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - next_cms_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  next_cms_network:
    external: true
    driver: bridge
