/*
 * @Author: Semmy Wong
 * @Date: 2024-01-30 16:20:04
 * @LastEditors: Semmy Wong
 * @LastEditTime: 2024-12-12 20:40:13
 * @Description: Description
 */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
